markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Paul Masurel
url: http://fulmicoton.com
description: I got an Idea!
twitter: fulmicoton
github: poulejapon
gravatar_url: http://gravatar.com/avatar/1cd46a26ceada395ae900bd4cd40a052